$(document).ready(function(){
    $("#button1").click(function(){
        $("#badr-hotels").fadeToggle(150);
    });
    $("#button2").click(function(){
        $("#bar-hotels").fadeToggle(150);
    });
    $("#button3").click(function(){
        $("#gupt-hotels").fadeToggle(150);
    });
    $("#button4").click(function(){
        $("#hari-hotels").fadeToggle(150);
    });
    $("#button5").click(function(){
        $("#jan-hotels").fadeToggle(150);
    });
    $("#button6").click(function(){
        $("#jos-hotels").fadeToggle(150);
    });
    $("#button7").click(function(){
        $("#phata-hotels").fadeToggle(150);
    });
    $("#button8").click(function(){
        $("#pip-hotels").fadeToggle(150);
    });
    $("#button9").click(function(){
        $("#rish-hotels").fadeToggle(150);
    });
    $("#button10").click(function(){
        $("#rudr-hotels").fadeToggle(150);
    });
    $("#button11").click(function(){
        $("#sita-hotels").fadeToggle(150);
    });
    $("#button12").click(function(){
        $("#utt-hotels").fadeToggle(150);
    });
    $("#button13").click(function(){
        $("#ked-hotels").fadeToggle(150);
    });
});